CREATE USER M_ElHagez IDENTIFIED BY M_ElHagez;
ALTER USER M_ElHagez QUOTA unlimited ON SYSTEM;
GRANT CREATE SESSION, CONNECT, RESOURCE, DBA TO M_ElHagez;
GRANT ALL PRIVILEGES TO M_ElHagez;
COMMIT WORK; 
